services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis

  db:
    image: postgres:16

  redis:
    image: redis:7